# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
---
version: 2
updates:
  - package-ecosystem: "pip"  # See documentation for possible values
    directory: "/"  # Default location of package manifests (e.g., pyproject.toml)
    target-branch: "master"
    versioning-strategy: increase-if-necessary
    rebase-strategy: "disabled"
    allow:
      - dependency-name: "prettytable"
        dependency-type: "direct"
      - dependency-name: "tomli"
        dependency-type: "production"
      - dependency-name: "wcwidth"
        dependency-type: "production"
      # allow build/packaging transitive packages
      # (will only ever approve if already in pyproject.toml)
      - dependency-name: "build"
        dependency-type: "indirect"
      - dependency-name: "setuptools"
        dependency-type: "indirect"
      - dependency-name: "setuptools_scm"
        dependency-type: "indirect"
      - dependency-name: "pip"
        dependency-type: "indirect"
    ignore:
      - dependency-name: "*"
    exclude-paths:
      - "requirements.txt"
      - "*-requirements.txt"
      - "docker/*"
    assignees:
      - "reactive-firewall"
    commit-message:
      prefix: "[UPDATE] "
      include: "scope"
    schedule:
      interval: "weekly"
      day: "friday"
  - package-ecosystem: "pip"  # See documentation for possible values
    directory: "/"  # Location of package manifests
    target-branch: "next" # different to allow dependabot to work
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "direct"
    exclude-paths:
      - "pyproject.toml"
      - "docker/*"
    assignees:
      - "reactive-firewall"
    commit-message:
      prefix: "[SYNC] "
      include: "scope"
    schedule:
      interval: "weekly"
      day: "friday"
  - package-ecosystem: "github-actions"  # See documentation for possible values
    directory: ".github/workflows/"  # Location of package manifests
    target-branch: "master"
    # rebase-strategy: "disabled"  # enabled by default
    assignees:
      - "reactive-firewall"
    commit-message:
      prefix: "[UPDATE] "
      include: "scope"
    schedule:
      interval: "weekly"
      day: "friday"
