#!/usr/bin/env make -f

# Pip-Licenses Makefile
# ..................................
# Copyright (c) 2018-2024, raimon
# Copyright (c) 2024-2026, Mr. Walls
# ..................................
# Licensed under MIT (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# ..........................................
# https://github.com/raimon49/pip-licenses/tree/HEAD/LICENSE
# ..........................................
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ifeq "$(LANG)" ""
	LANG="en_US.UTF-8"
endif

ifeq "$(LC_CTYPE)" ""
	LC_CTYPE="en_US.UTF-8"
endif

ifndef SHELL
	SHELL:=command -pv bash
endif

ifeq "$(ERROR_LOG_PATH)" ""
	ERROR_LOG_PATH="/dev/null"
endif

# find correct python in cross-platform way
ifeq "$(COMMAND)" ""
	COMMAND_CMD!=`command -v xcrun || command which which || command -v which || command -v command`
	ifeq "$(COMMAND_CMD)" "*xcrun"
		COMMAND_ARGS=--find
	endif
	ifeq "$(COMMAND_CMD)" "*command"
		COMMAND_ARGS=-pv
	endif
	COMMAND=$(COMMAND_CMD) $(COMMAND_ARGS)
endif

ifeq "$(MAKE)" ""
	#  just no cmake please
	MAKEFLAGS=$(MAKEFLAGS) -s
	MAKE!=`$(COMMAND) make 2>$(ERROR_LOG_PATH) || $(COMMAND) gnumake 2>$(ERROR_LOG_PATH)`
endif

ifeq "$(ECHO)" ""
	ECHO=printf "%s\n"
endif

ifndef PYTHONUTF8
	PYTHONUTF8 := 1
endif

ifeq "$(PYTHON)" ""
	PY_CMD=$(COMMAND) python3
	ifneq "$(PY_CMD)" ""
		PY_ARGS=-B
	else
		PY_CMD=$(COMMAND) python
	endif
	PYTHON=$(PY_CMD) $(PY_ARGS)
endif

# SUPPORT PEP-517 with --use-pep517 when available

ifndef PIP_COMMON_FLAGS
	# Define probable pip install flags based on python command
	ifneq "$(PY_CMD)" ""
		# Define probable pip install flags
		PIP_PREFIX_FLAGS := --no-input
	else
		# Define common pip install flags
		PIP_PREFIX_FLAGS := --no-input
	endif
	# Define common pip install flags
	PIP_COMMON_FLAGS := --exists-action s --upgrade --upgrade-strategy eager
endif

ifeq "$(LOG)" ""
	LOG=no
endif

ifeq "$(LOG)" "no"
	QUIET=@
	ifeq "$(DO_FAIL)" ""
		DO_FAIL=$(COMMAND) true
	endif
endif

# else
ifeq "$(DO_FAIL)" ""
	DO_FAIL=$(ECHO) "ok"
endif

ifeq "$(RM)" ""
	RM=$(COMMAND) rm -f
endif

ifeq "$(RMDIR)" ""
	RMDIR=$(RM)rd
endif

# based on remote (requires remote named origin)
# REPO_NAME:=$(shell basename -s .git `git remote get-url origin`)
# get the local clone directory name (always will exist in clones, even if you call your remote fork on github "github" and setup the remote "upstream")
REPO_NAME:=$(shell basename `git rev-parse --show-toplevel`)
# create a venv for THIS git clone (allows developers to have multiple clones if needed)
VENV_NAME:='venv/$(REPO_NAME)'
# file path to extra developer requirements generated by pip-compile
DEV_DEPENDS:='dev-requirements'

.DEFAULT_GOAL:= help
.PHONY: help, setup, local-install, local-uninstall, update-depends, lint, test, deploy, test-deploy, build, clean, full-clean, un-setup

help:
	@echo 'Usage: make <subcommand>'
	@echo ''
	@echo 'Subcommands:'
	@echo '    setup           Setup for development'
	@echo '    local-install   Install locally'
	@echo '    local-uninstall Uninstall locally'
	@echo '    local-ci-check  Run acceptance tests and linting checks locally'
	@echo '    update-depends  Re-compile requirements for development'
	@echo '    build           Build package'
	@echo '    lint            Re-lint formatting and typing with pyproject.toml'
	@echo '    test            Run project tests'
	@echo '    clean           Clean directories'
	@echo '    deploy          Unused & Deprecated (Previously Release to PyPI server)'
	@echo '    test-deploy     Unused & Deprecated (previously released to Test PyPI server)'

# utility for some developer environments
venv:
	test -d $@ || mkdir -m 755 ./$@

$(VENV_NAME): venv
	test -d $(VENV_NAME) || $(PYTHON) -m venv $(VENV_NAME)
	$(QUIET)test -d $(VENV_NAME) || exit 1 ;

setup: $(VENV_NAME)
	$(QUIET)$(VENV_NAME)/bin/python -B -m ensurepip || exit 2 ;
	$(VENV_NAME)/bin/python -B -m pip $(PIP_PREFIX_FLAGS) install $(PIP_COMMON_FLAGS) -r $(DEV_DEPENDS).txt

local-install: $(VENV_NAME)
	$(VENV_NAME)/bin/python -m pip $(PIP_PREFIX_FLAGS) install $(PIP_COMMON_FLAGS) -e .

local-uninstall:
	$(VENV_NAME)/bin/python -m pip $(PIP_PREFIX_FLAGS) uninstall -y pip-licenses

local-ci-check: build lint test
	$(QUIET)$(DO_FAIL)  # does nothing successfully (if reached)

update-depends:
	$(VENV_NAME)/bin/python -m pip-compile --extra dev -o dev-requirements.txt -U pyproject.toml

# developer workflow targets

build: clean
	$(VENV_NAME)/bin/python -m build

lint:
	$(VENV_NAME)/bin/python -m ruff check .
	$(VENV_NAME)/bin/python -m ruff format .
	$(VENV_NAME)/bin/python -m mypy --install-types --non-interactive .

test:
	$(VENV_NAME)/bin/python -m pytest

# cleanup and reset

clean:
	$(QUIET)$(RM) -r dist

full-clean:: local-uninstall clean
	$(RM) -vr *.egg-info 2>$(ERROR_LOG_PATH) || true ;
	$(RMDIR) -v ./{piplicenses,tests}/__pycache__ 2>$(ERROR_LOG_PATH) || true ;
	$(RMDIR) -v ./.coverage 2>$(ERROR_LOG_PATH) || true ;
	$(RMDIR) -v ./.mypy_cache 2>$(ERROR_LOG_PATH) || true ;
	$(RMDIR) -v ./.pytest_cache 2>$(ERROR_LOG_PATH) || true ;

un-setup:: full-clean
	$(RMDIR) -v ./venv 2>$(ERROR_LOG_PATH) || true ;

# historical targets, no-longer supported

deploy: build
	$(VENV_NAME)/bin/python -m twine upload dist/*

test-deploy: build
	$(VENV_NAME)/bin/python -m twine upload -r pypitest dist/*
