# based on remote (requires remote named origin)
# REPO_NAME:=$(shell basename -s .git `git remote get-url origin`)
# get the local clone directory name (always will exist in clones, even if you call your remote fork on github "github" and setup the remote "upstream")
REPO_NAME:=$(shell basename `git rev-parse --show-toplevel`)
# create a venv for THIS git clone (allows developers to have multiple clones if needed)
VENV_NAME:='venv/$(REPO_NAME)'
# file path to extra developer requirements generated by pip-compile
DEV_DEPENDS:='dev-requirements'

.DEFAULT_GOAL:= help
.PHONY: help, setup, local-install, local-uninstall, update-depends, lint, test, deploy, test-deploy, build, clean, full-clean, un-setup

help:
	@echo 'Usage: make <subcommand>'
	@echo ''
	@echo 'Subcommands:'
	@echo '    setup           Setup for development'
	@echo '    local-install   Install locally'
	@echo '    local-uninstall Uninstall locally'
	@echo '    update-depends  Re-compile requirements for development'
	@echo '    build           Build package'
	@echo '    lint            Re-lint formatting and typing with pyproject.toml'
	@echo '    test            Run project tests'
	@echo '    clean           Clean directories'
	@echo '    deploy          Unused & Deprecated (Previously Release to PyPI server)'
	@echo '    test-deploy     Unused & Deprecated (previously released to Test PyPI server)'

# utility for some developer environments
venv:
	test -d $@ || mkdir -m 755 ./$@

$(VENV_NAME): venv
	test -d $(VENV_NAME) || python -m venv $(VENV_NAME)
	test -d $(VENV_NAME) || exit 1 ;

setup: $(VENV_NAME)
	$(VENV_NAME)/bin/python -m pip install -r $(DEV_DEPENDS).txt

local-install: $(VENV_NAME)
	$(VENV_NAME)/bin/python -m pip install -e .

local-uninstall:
	$(VENV_NAME)/bin/python -m pip uninstall -y pip-licenses

update-depends:
	$(VENV_NAME)/bin/python -m pip-compile --extra dev -o dev-requirements.txt -U pyproject.toml

# developer workflow targets

build: clean
	$(VENV_NAME)/bin/python -m build

lint:
	$(VENV_NAME)/bin/python -m ruff check
	$(VENV_NAME)/bin/python -m ruff format
	$(VENV_NAME)/bin/python -m mypy --install-types --non-interactive .

test:
	$(VENV_NAME)/bin/python -m pytest

# cleanup and reset

clean:
	rm -rf dist

full-clean:: local-uninstall clean
	rm -vrf *.egg-info 2>/dev/null || true ;
	rm -vfrd ./{piplicenses,tests}/__pycache__ 2>/dev/null || true ;
	rm -vfrd ./.coverage 2>/dev/null || true ;
	rm -vfrd ./.mypy_cache 2>/dev/null || true ;
	rm -vfrd ./.pytest_cache 2>/dev/null || true ;

un-setup:: full-clean
	rm -vfrd ./venv 2>/dev/null || true ;

# historical targets, no-longer supported

deploy: build
	$(VENV_NAME)/bin/python -m twine upload dist/*

test-deploy: build
	$(VENV_NAME)/bin/python -m twine upload -r pypitest dist/*
